#!/usr/bin/env bash

ansible-playbook                                                              \
    --connection=local                                                        \
    -e ansible_python_interpreter=`which python3`                             \
    --tags ec2-create                                                         \
    iac.yml
