#!/usr/bin/env bash

export AWS_ACCESS_KEY_ID=AKIA4IQOAUCDEZKRMWHX
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=us-east-1

ansible-playbook                                                              \
    --connection=local                                                        \
    -e ansible_python_interpreter=`which python3`                             \
    --tags ec2-create                                                         \
    aws/deploy.yml
