---

- hosts: webserver
  gather_facts: true
  become: true
  pre_tasks:
    - name: Verify Ansible minimum version
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: >
          "You must update Ansible to at least 2.9"
  tasks:
    - name: test connection to remote
      wait_for_connection:

    - name: Update OS
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Configure Applications
      include_role:
        name: "{{ item }}"
      loop:
        - setup_mysql
        - setup_php
        - setup_nginx
        - setup_wordpress

...
