---
# Provision Playbook to deploy Wordpress onto a remote Ubuntu instance
- hosts: webserver
  gather_facts: true
  become: true
  vars:
    username: ansible
  pre_tasks:
    - name: Verify Ansible minimum version
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: >
          "You must update Ansible to at least 2.9"
  tasks:
    - name: Test connection to remote instance
      wait_for_connection:

    - name: Enable the Ubuntu universe repository
      apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://archive.ubuntu.com/ubuntu/ jammy universe"
        - "deb http://archive.ubuntu.com/ubuntu/ jammy-updates universe"
        - "deb http://security.ubuntu.com/ubuntu/ jammy-security universe"

    - name: Update Ubuntu OS
      ansible.builtin.apt:
        name: "*"
        state: latest
      tags:
        - update

    - name: Upgrade Ubuntu OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Configure Applications
      include_role:
        name: "{{ item }}"
      loop:
#        - setup_ufw_firewall
#        - setup_user
        - setup_mysql
        - setup_php
        - setup_nginx
        - setup_wordpress

...
