---

- hosts: localhost
  connection: local
  tasks:
    - name: Write SSH key file
      ansible.builtin.copy:
        content: "{{ ssh_key_data }}"
        dest: "{{ playbook_dir }}/id_ed25519"
        mode: "0644"

- hosts: webserver
  gather_facts: true
  become: true
  vars:
    ansible_host: "{{ remote_ip_address }}"
    ansible_user: "{{ ssh_user_name }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/id_ed25519"
  pre_tasks:
    - name: Verify Ansible minimum version
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: >
          "You must update Ansible to at least 2.9"
  tasks:
    - name: test connection to remote
      wait_for_connection:

    - name: Update OS
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Configure Applications
      include_role:
        name: "{{ item }}"
      loop:
        - setup_mysql
        - setup_php:
        - setup_nginx:
        - setup_wordpress:

...
