---
# Provision Playbook to deploy Wordpress onto a remote Ubuntu instance
- hosts: webserver
  gather_facts: true
  become: true
  vars:
    mysql_database_host: localhost
  pre_tasks:
    - name: Verify Ansible minimum version
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: >
          "You must update Ansible to at least 2.9"
  tasks:
    - name: Test connection to remote instance
      wait_for_connection:

    - name: Configure Applications
      include_role:
        name: "{{ item }}"
      loop:
        - setup_server
#        - setup_ufw_firewall
        - setup_mysql
        - setup_php
        - setup_nginx
        - setup_wordpress

...
