#!/usr/bin/env bash

ansible-playbook                                                              \
    --inventory inventory                                                     \
    --vault-id passwd                                                         \
     provision.yml
