#!/usr/bin/env bash

# ansible-vault decrypt inventory/group_vars/all/vault --vault-id passwd
# Populate the variables:
#  - ssh key
#  - ip address
#  - usernames
#  - passwords
# ansible-vault encrypt inventory/group_vars/all/vault --vault-id passwd

ansible-playbook                                                              \
    --inventory inventory                                                     \
    --vault-id passwd                                                         \
     provision.yml
