---
- name: start php
  ansible.builtin.service:
    name: php8.1-fpm
    state: started

- name: reload php
  ansible.builtin.service:
    name: php8.1-fpm
    state: reloaded

- name: restart php
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted
...