#!/usr/bin/env bash

export AWS_ACCESS_KEY_ID=AKIAR4REMUES4EOT2TLI
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=us-east-1

ansible-playbook                                                              \
    --connection=local                                                        \
    -e ansible_python_interpreter=`which python3`                             \
    --tags ec2-create                                                         \
    deploy.yml
