---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
     # TODO: Ansible minimum version check
     - name: Initialise
       debug:
         msg: "Local connection is OK"

- hosts: webservers
  gather_facts: yes
  become: yes
  tasks:
    - name: test connection to remote
      wait_for_connection:

    - name: Update OS
      apt:
        name: "*"
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
    
    - name: Configure Applications
      include_role:
        name: "{{ item }}"
      loop:
        - setupMysql
        - setupPhp
        - setupNginx
        - setupWordpress
    
...
