---

- name: Install nginx
  ansible.builting.apt:
    name: nginx
    state: latest

- name: Ensure nginx is running and enabled
  ansible.builtin.service:
    name: nginx
    state: running
    enabled: true

- name: Create WordPress application directory
  ansible.builtin.file:
    path: "{{ wordpress_application_path }}"
    owner: "{{ ansible_user }}"
    mode: "0644"
    state: directory

- name: Create the nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
    owner: "{{ ansible_user }}"
    mode: "0644"
    validate: nginx -t

- name: Create symbolic link to nginx configuration file for site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-available/wordpress.conf
    owner: "{{ ansible_user }}"
    mode: "0644"
    state: link

- name: Reload the nginx service
  ansible.builtin.service:
    name: nginx
    state: reloaded

...
