---

- name: Add Nginx repo
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/nginx

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    force: true
    update_cache: yes

- name: Create WordPress application directory
  ansible.builtin.file:
    path: "{{ wordpress_application_path }}"
    owner: "{{ ansible_user }}"
    mode: "0644"
    state: directory

- name: Create the nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
    owner: "{{ ansible_user }}"
    mode: "0644"
    validate: nginx -t

- name: Create symbolic link to nginx configuration file for site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-enabled/wordpress.conf
    owner: "{{ ansible_user }}"
    mode: "0644"
    state: link
  notify: reload nginx

- name: Set Nginx user
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "^user"
    line: "user {{ username }};"
    state: present
  notify: restart nginx

...
